name: Run Python script daily

on:
  schedule:
    - cron:  '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install requests mysql-connector-python

    - name: Run script
      env:
        STEAM_API_TOKEN: ${{ secrets.STEAM_API_TOKEN }}
        STEAM_API_ID: ${{ secrets.STEAM_API_ID }}
        GREPTIME_HOST: ${{ secrets.GREPTIME_HOST }}
        GREPTIME_PORT: ${{ secrets.GREPTIME_PORT }}
        GREPTIME_DATABASE: ${{ secrets.GREPTIME_DATABASE }}
        GREPTIME_USERNAME: ${{ secrets.GREPTIME_USERNAME }}
        GREPTIME_PASSWORD: ${{ secrets.GREPTIME_PASSWORD }}
      run: python main.py